# 项目相关配置
ruoyi:
  #名称
  name: RuoYi
  #版本
  version: 2.3.0
  #版权年份
  copyrightYear: 2018
  #头像上传路径
  profile: /profile/
  #头像回显路径
  showPath: http://106.14.126.108/profile/
  # 获取ip地址开关
  addressEnabled: false

# 数据源配置
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        druid:
            # 主库数据源
            master:
                url: jdbc:mysql://106.14.126.108:3306/mei?useUnicode=true&characterEncoding=utf8&useSSL=false
                username: mei
                password: Mei53200
            # 从库数据源
            slave:
                # 从数据源开关/默认关闭
                enabled: false
                url: 
                username: 
                password: 
            # 初始连接数
            initial-size: 10
            # 最大连接池数量
            max-active: 100
            # 最小连接池数量
            min-idle: 10
            # 配置获取连接等待超时的时间
            max-wait: 60000
            # 打开PSCache，并且指定每个连接上PSCache的大小
            pool-prepared-statements: true
            max-pool-prepared-statement-per-connection-size: 20
            # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
            timeBetweenEvictionRunsMillis: 60000
            # 配置一个连接在池中最小生存的时间，单位是毫秒
            min-evictable-idle-time-millis: 300000
            validation-query: SELECT 1 FROM DUAL
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            stat-view-servlet:
                enabled: true
                url-pattern: /monitor/druid/*
            filter:
                stat:
                    log-slow-sql: true
                    slow-sql-millis: 1000
                    merge-sql: false
                wall:
                    config:
                        multi-statement-allow: true
    cache:
        redis:
            use-key-prefix: true
            cache-null-values: false
            time-to-live: 30m
    redis:
        host: 106.14.126.108
        port: 6379
        password: Mei53200
        timeout: 20000
        jedis:
            pool:
                max-active: 8
                min-idle: 0
                max-idle: 8
                max-wait: -1
    rabbitmq:
        host: 106.14.126.108
        port: 5672
        username: mei
        password: Mei53200
    mail:
        host: smtp.163.com
        username: m17683837392@163.com
        password: Mei3993859
        default-encoding: utf-8
mail:
    fromMail:
        addr: m17683837392@163.com
        fromName: 梅式系统邮件