package com.ruoyi.mapper;

import com.ruoyi.entity.FileManage;
import com.ruoyi.entity.FileManageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FileManageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file_manage
     *
     * @mbggenerated
     */
    int countByExample(FileManageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file_manage
     *
     * @mbggenerated
     */
    int deleteByExample(FileManageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file_manage
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer fileId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file_manage
     *
     * @mbggenerated
     */
    int insert(FileManage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file_manage
     *
     * @mbggenerated
     */
    int insertSelective(FileManage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file_manage
     *
     * @mbggenerated
     */
    List<FileManage> selectByExample(FileManageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file_manage
     *
     * @mbggenerated
     */
    FileManage selectByPrimaryKey(Integer fileId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file_manage
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") FileManage record, @Param("example") FileManageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file_manage
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") FileManage record, @Param("example") FileManageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file_manage
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FileManage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file_manage
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FileManage record);
}