package com.ruoyi.mapper;

import com.ruoyi.entity.Tea;
import com.ruoyi.entity.TeaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TeaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tea
     *
     * @mbggenerated
     */
    int countByExample(TeaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tea
     *
     * @mbggenerated
     */
    int deleteByExample(TeaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tea
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer teaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tea
     *
     * @mbggenerated
     */
    int insert(Tea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tea
     *
     * @mbggenerated
     */
    int insertSelective(Tea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tea
     *
     * @mbggenerated
     */
    List<Tea> selectByExample(TeaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tea
     *
     * @mbggenerated
     */
    Tea selectByPrimaryKey(Integer teaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tea
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Tea record, @Param("example") TeaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tea
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Tea record, @Param("example") TeaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tea
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Tea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tea
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Tea record);
}