package com.ruoyi.mapper;

import com.ruoyi.entity.TeaManager;
import com.ruoyi.entity.TeaManagerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TeaManagerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tea_manager
     *
     * @mbggenerated
     */
    int countByExample(TeaManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tea_manager
     *
     * @mbggenerated
     */
    int deleteByExample(TeaManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tea_manager
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer teaManagerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tea_manager
     *
     * @mbggenerated
     */
    int insert(TeaManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tea_manager
     *
     * @mbggenerated
     */
    int insertSelective(TeaManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tea_manager
     *
     * @mbggenerated
     */
    List<TeaManager> selectByExample(TeaManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tea_manager
     *
     * @mbggenerated
     */
    TeaManager selectByPrimaryKey(Integer teaManagerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tea_manager
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TeaManager record, @Param("example") TeaManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tea_manager
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TeaManager record, @Param("example") TeaManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tea_manager
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TeaManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tea_manager
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TeaManager record);
}