package com.ruoyi.mapper;

import com.ruoyi.entity.TestGenerator;
import com.ruoyi.entity.TestGeneratorExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TestGeneratorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test_generator
     *
     * @mbggenerated
     */
    int countByExample(TestGeneratorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test_generator
     *
     * @mbggenerated
     */
    int deleteByExample(TestGeneratorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test_generator
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test_generator
     *
     * @mbggenerated
     */
    int insert(TestGenerator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test_generator
     *
     * @mbggenerated
     */
    int insertSelective(TestGenerator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test_generator
     *
     * @mbggenerated
     */
    List<TestGenerator> selectByExample(TestGeneratorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test_generator
     *
     * @mbggenerated
     */
    TestGenerator selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test_generator
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TestGenerator record, @Param("example") TestGeneratorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test_generator
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TestGenerator record, @Param("example") TestGeneratorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test_generator
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TestGenerator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test_generator
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TestGenerator record);
}