package com.ruoyi.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CourseArrangementExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_course_arrangement
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_course_arrangement
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_course_arrangement
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_arrangement
     *
     * @mbggenerated
     */
    public CourseArrangementExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_arrangement
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_arrangement
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_arrangement
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_arrangement
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_arrangement
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_arrangement
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_arrangement
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_arrangement
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_arrangement
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_arrangement
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_course_arrangement
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCourseArrangementIdIsNull() {
            addCriterion("course_arrangement_id is null");
            return (Criteria) this;
        }

        public Criteria andCourseArrangementIdIsNotNull() {
            addCriterion("course_arrangement_id is not null");
            return (Criteria) this;
        }

        public Criteria andCourseArrangementIdEqualTo(Integer value) {
            addCriterion("course_arrangement_id =", value, "courseArrangementId");
            return (Criteria) this;
        }

        public Criteria andCourseArrangementIdNotEqualTo(Integer value) {
            addCriterion("course_arrangement_id <>", value, "courseArrangementId");
            return (Criteria) this;
        }

        public Criteria andCourseArrangementIdGreaterThan(Integer value) {
            addCriterion("course_arrangement_id >", value, "courseArrangementId");
            return (Criteria) this;
        }

        public Criteria andCourseArrangementIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("course_arrangement_id >=", value, "courseArrangementId");
            return (Criteria) this;
        }

        public Criteria andCourseArrangementIdLessThan(Integer value) {
            addCriterion("course_arrangement_id <", value, "courseArrangementId");
            return (Criteria) this;
        }

        public Criteria andCourseArrangementIdLessThanOrEqualTo(Integer value) {
            addCriterion("course_arrangement_id <=", value, "courseArrangementId");
            return (Criteria) this;
        }

        public Criteria andCourseArrangementIdIn(List<Integer> values) {
            addCriterion("course_arrangement_id in", values, "courseArrangementId");
            return (Criteria) this;
        }

        public Criteria andCourseArrangementIdNotIn(List<Integer> values) {
            addCriterion("course_arrangement_id not in", values, "courseArrangementId");
            return (Criteria) this;
        }

        public Criteria andCourseArrangementIdBetween(Integer value1, Integer value2) {
            addCriterion("course_arrangement_id between", value1, value2, "courseArrangementId");
            return (Criteria) this;
        }

        public Criteria andCourseArrangementIdNotBetween(Integer value1, Integer value2) {
            addCriterion("course_arrangement_id not between", value1, value2, "courseArrangementId");
            return (Criteria) this;
        }

        public Criteria andTeaManmgerIdIsNull() {
            addCriterion("tea_manmger_id is null");
            return (Criteria) this;
        }

        public Criteria andTeaManmgerIdIsNotNull() {
            addCriterion("tea_manmger_id is not null");
            return (Criteria) this;
        }

        public Criteria andTeaManmgerIdEqualTo(Integer value) {
            addCriterion("tea_manmger_id =", value, "teaManmgerId");
            return (Criteria) this;
        }

        public Criteria andTeaManmgerIdNotEqualTo(Integer value) {
            addCriterion("tea_manmger_id <>", value, "teaManmgerId");
            return (Criteria) this;
        }

        public Criteria andTeaManmgerIdGreaterThan(Integer value) {
            addCriterion("tea_manmger_id >", value, "teaManmgerId");
            return (Criteria) this;
        }

        public Criteria andTeaManmgerIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("tea_manmger_id >=", value, "teaManmgerId");
            return (Criteria) this;
        }

        public Criteria andTeaManmgerIdLessThan(Integer value) {
            addCriterion("tea_manmger_id <", value, "teaManmgerId");
            return (Criteria) this;
        }

        public Criteria andTeaManmgerIdLessThanOrEqualTo(Integer value) {
            addCriterion("tea_manmger_id <=", value, "teaManmgerId");
            return (Criteria) this;
        }

        public Criteria andTeaManmgerIdIn(List<Integer> values) {
            addCriterion("tea_manmger_id in", values, "teaManmgerId");
            return (Criteria) this;
        }

        public Criteria andTeaManmgerIdNotIn(List<Integer> values) {
            addCriterion("tea_manmger_id not in", values, "teaManmgerId");
            return (Criteria) this;
        }

        public Criteria andTeaManmgerIdBetween(Integer value1, Integer value2) {
            addCriterion("tea_manmger_id between", value1, value2, "teaManmgerId");
            return (Criteria) this;
        }

        public Criteria andTeaManmgerIdNotBetween(Integer value1, Integer value2) {
            addCriterion("tea_manmger_id not between", value1, value2, "teaManmgerId");
            return (Criteria) this;
        }

        public Criteria andStartTimeIsNull() {
            addCriterion("start_time is null");
            return (Criteria) this;
        }

        public Criteria andStartTimeIsNotNull() {
            addCriterion("start_time is not null");
            return (Criteria) this;
        }

        public Criteria andStartTimeEqualTo(Date value) {
            addCriterion("start_time =", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotEqualTo(Date value) {
            addCriterion("start_time <>", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeGreaterThan(Date value) {
            addCriterion("start_time >", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("start_time >=", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLessThan(Date value) {
            addCriterion("start_time <", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLessThanOrEqualTo(Date value) {
            addCriterion("start_time <=", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeIn(List<Date> values) {
            addCriterion("start_time in", values, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotIn(List<Date> values) {
            addCriterion("start_time not in", values, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeBetween(Date value1, Date value2) {
            addCriterion("start_time between", value1, value2, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotBetween(Date value1, Date value2) {
            addCriterion("start_time not between", value1, value2, "startTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNull() {
            addCriterion("end_time is null");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNotNull() {
            addCriterion("end_time is not null");
            return (Criteria) this;
        }

        public Criteria andEndTimeEqualTo(Date value) {
            addCriterion("end_time =", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotEqualTo(Date value) {
            addCriterion("end_time <>", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThan(Date value) {
            addCriterion("end_time >", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("end_time >=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThan(Date value) {
            addCriterion("end_time <", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("end_time <=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIn(List<Date> values) {
            addCriterion("end_time in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotIn(List<Date> values) {
            addCriterion("end_time not in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeBetween(Date value1, Date value2) {
            addCriterion("end_time between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("end_time not between", value1, value2, "endTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_course_arrangement
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_course_arrangement
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}