package com.ruoyi.entity;

import java.util.Date;

public class CourseArrangement {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course_arrangement.course_arrangement_id
     *
     * @mbggenerated
     */
    private Integer courseArrangementId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course_arrangement.tea_manmger_id
     *
     * @mbggenerated
     */
    private Integer teaManmgerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course_arrangement.start_time
     *
     * @mbggenerated
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course_arrangement.end_time
     *
     * @mbggenerated
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course_arrangement.status
     *
     * @mbggenerated
     */
    private Boolean status;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_arrangement
     *
     * @mbggenerated
     */
    public CourseArrangement(Integer courseArrangementId, Integer teaManmgerId, Date startTime, Date endTime, Boolean status) {
        this.courseArrangementId = courseArrangementId;
        this.teaManmgerId = teaManmgerId;
        this.startTime = startTime;
        this.endTime = endTime;
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_arrangement
     *
     * @mbggenerated
     */
    public CourseArrangement() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course_arrangement.course_arrangement_id
     *
     * @return the value of t_course_arrangement.course_arrangement_id
     *
     * @mbggenerated
     */
    public Integer getCourseArrangementId() {
        return courseArrangementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course_arrangement.course_arrangement_id
     *
     * @param courseArrangementId the value for t_course_arrangement.course_arrangement_id
     *
     * @mbggenerated
     */
    public void setCourseArrangementId(Integer courseArrangementId) {
        this.courseArrangementId = courseArrangementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course_arrangement.tea_manmger_id
     *
     * @return the value of t_course_arrangement.tea_manmger_id
     *
     * @mbggenerated
     */
    public Integer getTeaManmgerId() {
        return teaManmgerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course_arrangement.tea_manmger_id
     *
     * @param teaManmgerId the value for t_course_arrangement.tea_manmger_id
     *
     * @mbggenerated
     */
    public void setTeaManmgerId(Integer teaManmgerId) {
        this.teaManmgerId = teaManmgerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course_arrangement.start_time
     *
     * @return the value of t_course_arrangement.start_time
     *
     * @mbggenerated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course_arrangement.start_time
     *
     * @param startTime the value for t_course_arrangement.start_time
     *
     * @mbggenerated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course_arrangement.end_time
     *
     * @return the value of t_course_arrangement.end_time
     *
     * @mbggenerated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course_arrangement.end_time
     *
     * @param endTime the value for t_course_arrangement.end_time
     *
     * @mbggenerated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course_arrangement.status
     *
     * @return the value of t_course_arrangement.status
     *
     * @mbggenerated
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course_arrangement.status
     *
     * @param status the value for t_course_arrangement.status
     *
     * @mbggenerated
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }
}