package com.ruoyi.entity;

public class Stu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stu.stu_id
     *
     * @mbggenerated
     */
    private Integer stuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stu.sex
     *
     * @mbggenerated
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stu.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stu.grade_id
     *
     * @mbggenerated
     */
    private Integer gradeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stu
     *
     * @mbggenerated
     */
    public Stu(Integer stuId, String sex, String name, Integer gradeId) {
        this.stuId = stuId;
        this.sex = sex;
        this.name = name;
        this.gradeId = gradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stu
     *
     * @mbggenerated
     */
    public Stu() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stu.stu_id
     *
     * @return the value of t_stu.stu_id
     *
     * @mbggenerated
     */
    public Integer getStuId() {
        return stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stu.stu_id
     *
     * @param stuId the value for t_stu.stu_id
     *
     * @mbggenerated
     */
    public void setStuId(Integer stuId) {
        this.stuId = stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stu.sex
     *
     * @return the value of t_stu.sex
     *
     * @mbggenerated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stu.sex
     *
     * @param sex the value for t_stu.sex
     *
     * @mbggenerated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stu.name
     *
     * @return the value of t_stu.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stu.name
     *
     * @param name the value for t_stu.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stu.grade_id
     *
     * @return the value of t_stu.grade_id
     *
     * @mbggenerated
     */
    public Integer getGradeId() {
        return gradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stu.grade_id
     *
     * @param gradeId the value for t_stu.grade_id
     *
     * @mbggenerated
     */
    public void setGradeId(Integer gradeId) {
        this.gradeId = gradeId;
    }
}