package com.ruoyi.entity;

public class TeaManager {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tea_manager.tea_manager_id
     *
     * @mbggenerated
     */
    private Integer teaManagerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tea_manager.tea_id
     *
     * @mbggenerated
     */
    private Integer teaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tea_manager.subject_type
     *
     * @mbggenerated
     */
    private Integer subjectType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tea_manager.grade_id
     *
     * @mbggenerated
     */
    private Integer gradeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tea_manager
     *
     * @mbggenerated
     */
    public TeaManager(Integer teaManagerId, Integer teaId, Integer subjectType, Integer gradeId) {
        this.teaManagerId = teaManagerId;
        this.teaId = teaId;
        this.subjectType = subjectType;
        this.gradeId = gradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tea_manager
     *
     * @mbggenerated
     */
    public TeaManager() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tea_manager.tea_manager_id
     *
     * @return the value of t_tea_manager.tea_manager_id
     *
     * @mbggenerated
     */
    public Integer getTeaManagerId() {
        return teaManagerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tea_manager.tea_manager_id
     *
     * @param teaManagerId the value for t_tea_manager.tea_manager_id
     *
     * @mbggenerated
     */
    public void setTeaManagerId(Integer teaManagerId) {
        this.teaManagerId = teaManagerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tea_manager.tea_id
     *
     * @return the value of t_tea_manager.tea_id
     *
     * @mbggenerated
     */
    public Integer getTeaId() {
        return teaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tea_manager.tea_id
     *
     * @param teaId the value for t_tea_manager.tea_id
     *
     * @mbggenerated
     */
    public void setTeaId(Integer teaId) {
        this.teaId = teaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tea_manager.subject_type
     *
     * @return the value of t_tea_manager.subject_type
     *
     * @mbggenerated
     */
    public Integer getSubjectType() {
        return subjectType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tea_manager.subject_type
     *
     * @param subjectType the value for t_tea_manager.subject_type
     *
     * @mbggenerated
     */
    public void setSubjectType(Integer subjectType) {
        this.subjectType = subjectType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tea_manager.grade_id
     *
     * @return the value of t_tea_manager.grade_id
     *
     * @mbggenerated
     */
    public Integer getGradeId() {
        return gradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tea_manager.grade_id
     *
     * @param gradeId the value for t_tea_manager.grade_id
     *
     * @mbggenerated
     */
    public void setGradeId(Integer gradeId) {
        this.gradeId = gradeId;
    }
}